// export const GET_ALL_RECIPES = "GET_ALL_RECIPES";
export const SEARCH_RECIPES_REQUEST = 'SEARCH_RECIPES_REQUEST';
export const SEARCH_RECIPES_SUCCESS = 'SEARCH_RECIPES_SUCCESS';
export const SEARCH_RECIPES_FAILURE = 'SEARCH_RECIPES_FAILURE';

export const SEARCH_SINGLE_RECIPE_REQUEST = 'SEARCH_SINGLE_RECIPE_REQUEST';
export const SEARCH_SINGLE_RECIPE_SUCCESS = 'SEARCH_SINGLE_RECIPE_SUCCESS';
export const SEARCH_SINGLE_RECIPE_FAILURE = 'SEARCH_SINGLE_RECIPE_FAILURE';

export const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT';
export const CHANGE_INIT = 'CHANGE_INIT';
