// export const GET_ALL_RECIPES = "GET_ALL_RECIPES";
export const SEARCH_RECIPES_REQUEST = 'SEARCH_RECIPES_REQUEST';
export const SEARCH_RECIPES_SUCCESS = 'SEARCH_RECIPES_SUCCESS';
export const SEARCH_RECIPES_FAILURE = 'SEARCH_RECIPES_FAILURE';

export const SEARCH_TEXT = 'SEARCH_TEXT';
